# Render deployment configuration for SQLGym backend
services:
  - type: web
    name: sqlgym-backend
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: cd api && uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    healthCheckPath: /
    autoDeploy: true
    
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      
      # Frontend URL (set after frontend deployment)
      - key: FRONTEND_URL
        sync: false
      
      # Database
      - key: DATABASE_URL
        fromDatabase:
          name: sqlgym-db
          property: connectionString
      
      # Resend Email
      - key: RESEND_API_KEY
        sync: false
      - key: FROM_EMAIL
        sync: false
      
      # AWS S3
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_BUCKET_NAME
        sync: false
      - key: AWS_REGION
        sync: false
      
      # Google Gemini
      - key: GEMINI_API_KEY
        sync: false
      
      # OAuth (Optional)
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      
      # Security
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_SECRET_KEY
        generateValue: true

databases:
  - name: sqlgym-db
    databaseName: sqlgym
    plan: free
    user: sqlgym
